# Generated by Django 6.0.7 on 2026-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_student_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unkown', max_length=100),
        ),
    ]
